// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Conversations struct {
	ID        int64
	UserID    sql.NullInt64
	Uuid      string
	Title     sql.NullString
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

type Llms struct {
	ID           int64
	String       string
	Name         string
	ProviderID   int64
	ContextSize  int64
	Capabilities sql.NullString
	IsEnabled    int64
	CreatedAt    int64
	UpdatedAt    int64
}

type Messages struct {
	ID              int64
	ConversationID  sql.NullInt64
	ParentID        sql.NullInt64
	Role            string
	Content         string
	ContentRendered sql.NullString
	LlmID           sql.NullInt64
	BranchPath      sql.NullString
	CreatedAt       sql.NullInt64
}

type Providers struct {
	ID        int64
	Type      string
	Url       string
	CreatedAt int64
}

type Users struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt sql.NullInt64
}
