// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Conversation struct {
	ID        int64
	UserID    int64
	Uuid      string
	Title     sql.NullString
	IsPinned  int64
	CreatedAt int64
	UpdatedAt int64
}

type Llm struct {
	ID           int64
	String       string
	Name         string
	ProviderID   int64
	ContextSize  int64
	Capabilities sql.NullString
	IsEnabled    int64
	CreatedAt    int64
	UpdatedAt    int64
}

type Message struct {
	ID              int64
	ConversationID  int64
	ParentID        sql.NullInt64
	Role            string
	Content         string
	ContentRendered sql.NullString
	LlmID           int64
	CreatedAt       int64
}

type Provider struct {
	ID        int64
	Type      string
	Url       string
	CreatedAt int64
}

type User struct {
	ID        int64
	Email     string
	Name      sql.NullString
	CreatedAt int64
}
