// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addConversation = `-- name: AddConversation :one
INSERT INTO conversations (user_id, uuid) VALUES (?, ?) RETURNING id, user_id, uuid, title, created_at, updated_at
`

type AddConversationParams struct {
	UserID int64
	Uuid   string
}

func (q *Queries) AddConversation(ctx context.Context, arg AddConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, addConversation, arg.UserID, arg.Uuid)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addLLM = `-- name: AddLLM :one
INSERT INTO llms (string, name, provider_id, context_size) VALUES (?, ?, ?, ?) RETURNING id, string, name, provider_id, context_size, capabilities, is_enabled, created_at, updated_at
`

type AddLLMParams struct {
	String      string
	Name        string
	ProviderID  int64
	ContextSize int64
}

func (q *Queries) AddLLM(ctx context.Context, arg AddLLMParams) (Llm, error) {
	row := q.db.QueryRowContext(ctx, addLLM,
		arg.String,
		arg.Name,
		arg.ProviderID,
		arg.ContextSize,
	)
	var i Llm
	err := row.Scan(
		&i.ID,
		&i.String,
		&i.Name,
		&i.ProviderID,
		&i.ContextSize,
		&i.Capabilities,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addProvider = `-- name: AddProvider :one
INSERT INTO providers (type, url) VALUES (?, ?) RETURNING id, type, url, created_at
`

type AddProviderParams struct {
	Type string
	Url  string
}

func (q *Queries) AddProvider(ctx context.Context, arg AddProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, addProvider, arg.Type, arg.Url)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_id, uuid, title, created_at, updated_at FROM conversations WHERE id = ? LIMIT 1
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByUUID = `-- name: GetConversationByUUID :one
SELECT id, user_id, uuid, title, created_at, updated_at FROM conversations WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetConversationByUUID(ctx context.Context, uuid string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByUUID, uuid)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT id, user_id, uuid, title, created_at, updated_at FROM conversations WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) GetConversationsByUserID(ctx context.Context, userID int64) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Uuid,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLLMs = `-- name: GetLLMs :many
SELECT id, string, name, provider_id, context_size, capabilities, is_enabled, created_at, updated_at FROM llms ORDER BY id
`

func (q *Queries) GetLLMs(ctx context.Context) ([]Llm, error) {
	rows, err := q.db.QueryContext(ctx, getLLMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Llm
	for rows.Next() {
		var i Llm
		if err := rows.Scan(
			&i.ID,
			&i.String,
			&i.Name,
			&i.ProviderID,
			&i.ContextSize,
			&i.Capabilities,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviders = `-- name: GetProviders :many
SELECT id, type, url, created_at FROM providers ORDER BY id
`

func (q *Queries) GetProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, getProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations set title = ?, updated_at = unixepoch('now') WHERE uuid = ?
`

type UpdateConversationTitleParams struct {
	Title sql.NullString
	Uuid  string
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationTitle, arg.Title, arg.Uuid)
	return err
}
